#ifndef NNFILETYPE_H
#define NNFILETYPE_H

enum class NNFileType
{
    UNIFIED_TRAINING_DATA,
    IDX_MNIST_LIKE_LABELS,
    IDX_MNSIT_LIKE_SAMPELS,
    ONE_TRAINING_EXAMPLE_ONLY,
    ONE_LINE_WEIGHTS,
    MATRIX_WEIGHTS
};

#endif // NNFILETYPE_H
